services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - mono_repo_data:/code/mono_repo.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - API_HOST=http://backend:8000
    restart: unless-stopped

volumes:
  mono_repo_data:
